FROM jhonathas/vzon-node:8.9.4

MAINTAINER Jhonathas Matos <jhonathas@gmail.com>

# Pull latest asdf

RUN asdf update --head

# Install dependencies

RUN apt-get install -y build-essential autoconf libncurses5-dev libssh-dev unzip
RUN apt-get install -y postgresql-client

RUN asdf plugin-add erlang
RUN asdf plugin-add elixir

RUN asdf install erlang 21.0.7
RUN asdf global erlang 21.0.7

RUN asdf install elixir 1.7.3
RUN asdf global elixir 1.7.3
