FROM jhonathas/vzon-node:8.9.4

MAINTAINER Jhonathas Matos <jhonathas@gmail.com>

# Pull latest asdf

RUN asdf update --head

# Install dependencies

RUN apt-get install -y build-essential autoconf libncurses5-dev libssh-dev unzip
RUN apt-get install -y postgresql-client

RUN asdf plugin-add erlang
RUN asdf plugin-add elixir

RUN asdf install erlang 21.0.7
RUN asdf global erlang 21.0.7

RUN asdf install elixir 1.7.3
RUN asdf global elixir 1.7.3

# Chromedriver

RUN CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
    mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION && \
    curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION && \
    rm /tmp/chromedriver_linux64.zip && \
    chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver && \
    ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver

# Set Locale

ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="America/Sao_Paulo"

RUN apt-get install -y --no-install-recommends locales
RUN echo $LANG UTF-8 > /etc/locale.gen
RUN locale-gen
RUN update-locale LANG=$LANG

RUN mix do local.hex --force, local.rebar --force
